### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by kriscoleman** [natkuhn/Chrome-debug#1]
I'm pretty sure this is meant to go into our global path as it is just a bash script, but it would be helpful if there were installation steps or "how to use" steps in the readme. 

**EDIT:** I think maybe it's just as easy as cloning the repo and dragging the `Chrome.debug` package to the menu bar, now that I've played with it. I did have to take some extra steps though to get the icon to work with the package. 

Also, thanks for putting this together and sharing!

**Comment by kriscoleman** [comment]
also, it might be super neat if this was available as a homebrew install, this could eliminate the manual work of cloning the repo and setting it up properly

**Comment by natkuhn** [comment]
I realized that the super-simple way to do this is to make a .dmg of the finished product. Much simpler than homebrew, I think! No need to put on your global path. I also realized that the documentation was not very clear, so I did some reorganization when I added the new instructions.

Thank you for your interest, and your feedback.
